'use strict';
let data=[],category='',limit=24,font=22;const $=id=>document.getElementById(id);const groups=['Молитвы','Акафисты','Святые и образы','По имени','Основы веры','Псалтирь','Аудио','Календарь'];
const normalize=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ё/g,'е');
const aliases={'николай':['никола'],'сергей':['серги'],'сергий':['серги'],'матрона':['матрон'],'спиридон':['спиридон'],'ксения':['ксени'],'петр и феврония':['петр','феврон'],'наталья':['натали','наталь'],'ангел хранитель':['ангел'],'10 заповедей':['заповед'],'7 смертных грехов':['смертн'],'о сыне':['детях','детей','матери'],'о дочери':['детях','детей','дочер'],'о муже':['браке','семейн','супруг','воин'],'о здоровье':['болящ','болезн','исцел'],'от злых людей':['обидящ','врагов','клевет','притеснен'],'в трудной ситуации':['скорб','бедств','отчаян','неудач'],'об исполнении благого прошения':['доброе дело','всякого дела','молитвы']};
function match(r,q){const hay=normalize(r.title+' '+r.section);if(!q)return true;if(aliases[q])return aliases[q].some(t=>hay.includes(t));return q.split(/\s+/).every(t=>hay.includes(t));}
function element(tag,text,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;}
function render(){const q=normalize($('search').value.trim()),section=$('section').value;const found=data.filter(r=>(!category||r.category===category)&&(!section||r.section===section)&&match(r,q));$('results-title').textContent=category||'Все материалы';$('count').textContent=`Найдено: ${found.length} · В библиотеке: ${data.length}`;$('name-note').hidden=category!=='По имени';$('results').replaceChildren();
for(const r of found.slice(0,limit)){const card=element('article',null,'card');card.append(element('div',r.section,'category'),element('h3',r.title),element('div','Источник: '+r.source,'meta'));const actions=element('div',null,'actions');if(r.text){const btn=element('button','Читать здесь');btn.onclick=()=>read(r);actions.append(btn);}const link=element('a',r.kind==='Святые с этим именем'?'Выбрать святого':r.category==='Аудио'?'Слушать у источника':r.text?'Первоисточник':'Открыть материал');link.href=r.url;link.target='_blank';link.rel='noopener';actions.append(link);card.append(actions);$('results').append(card);}
if(!found.length)$('results').append(element('p','Ничего не найдено. Попробуйте имя святого или более короткий запрос: «дети», «семья», «Николай».'));$('more').hidden=found.length<=limit;document.querySelectorAll('#categories button').forEach(b=>{b.classList.toggle('active',b.dataset.category===category);b.setAttribute('aria-pressed',b.dataset.category===category)});const params=new URLSearchParams();if(category)params.set('category',category);if($('search').value)params.set('q',$('search').value);history.replaceState(null,'',location.pathname+(params.size?'?'+params:'')+location.hash);}
function sections(){const vals=[...new Set(data.filter(r=>!category||r.category===category).map(r=>r.section))].sort((a,b)=>a.localeCompare(b,'ru'));$('section').replaceChildren(new Option('Все темы',''));vals.forEach(v=>$('section').append(new Option(v,v)));}
function read(r){$('reader-title').textContent=r.title;$('reader-text').textContent=r.text;$('reader-source').replaceChildren();const a=element('a','Источник: '+r.source);a.href=r.url;a.target='_blank';a.rel='noopener';$('reader-source').append(a);$('copy').textContent='Скопировать текст';$('reader').showModal();}
async function init(){try{const res=await fetch('/library-data.json');if(!res.ok)throw Error();data=await res.json();$('error').hidden=true;$('categories').replaceChildren();for(const name of ['',...groups]){const btn=element('button',name||'Все материалы');btn.dataset.category=name;btn.append(element('span',String(data.filter(r=>!name||r.category===name).length)));btn.onclick=()=>{category=name;limit=24;sections();render()};$('categories').append(btn);}const params=new URLSearchParams(location.search);category=groups.includes(params.get('category'))?params.get('category'):'';$('search').value=params.get('q')||'';sections();render();}catch{$('error').hidden=false;$('count').textContent='Библиотека временно недоступна';}}
$('search-form').onsubmit=e=>{e.preventDefault();limit=24;render()};$('search').oninput=()=>{limit=24;render()};$('section').onchange=()=>{limit=24;render()};$('more').onclick=()=>{limit+=24;render()};$('retry').onclick=init;document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{category='';$('search').value=b.dataset.query;limit=24;sections();render()});$('close').onclick=()=>$('reader').close();$('smaller').onclick=()=>{font=Math.max(16,font-2);$('reader-text').style.fontSize=font+'px'};$('larger').onclick=()=>{font=Math.min(40,font+2);$('reader-text').style.fontSize=font+'px'};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('reader-text').textContent);$('copy').textContent='Скопировано'}catch{$('copy').textContent='Выделите текст для копирования'}};init();
